version: "2"

services:
  web:
    build: .
    depends_on:
      - db
    volumes:
      - .:/var/www/app
    ports:
      - "3000:3000"

  db:
    image: postgres:9.6
    volumes:
      - /var/lib/postgresql/data
