version: "2"

services:
  web:
    build: .
    depends_on:
      - db
    networks:
      - db

  db:
    image: postgres:9.6
    volumes:
      - /var/lib/postgresql/data
    networks:
      - db
networks:
  db:

