default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: db
  user: postgres
  password: mysecretpassword

development:
  <<: *default
  database: todomvc_development

test:
  <<: *default
  database: todomvc_test

production:
  <<: *default
  database: todomvc_production
